# Generated by Django 3.2.3 on 2025-08-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('data_atualização', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
